#
# Copyright (C) 2019 - 2020 Rabobank Nederland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

spring:
  data:
    mongodb:
      uri: mongodb://localhost/test
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      client:
        registration:
          azure:
            client-name: azure
            clientId: <replace>
            clientSecret: <replace>
            redirectUri: "{baseUrl}/api/oauth2/callback/{registrationId}"
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - https://graph.microsoft.com/User.Read
        provider:
          azure:
            authorizationUri: http://localhost:8087/oauth2/v2.0/authorize
            tokenUri: http://localhost:8087/oauth2/v2.0/token
            userInfoUri: http://localhost:8087/v1.0/me
            user-name-attribute: displayName

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        include: ''
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

jwt:
  token:
    expiration: PT48H
    # replace with the result of com.rabobank.argos.service.security.TokenProvider.main
    secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==


  # After successfully authenticating with the OAuth2 Provider,
  # we'll be generating an auth token for the user and sending the token to the
  # redirectUri mentioned by the client in the /oauth2/authorize request.
  # We're not using cookies because they won't work well in mobile clients.
auth:
  frontendRedirectBasePath: http://localhost:8087

logging:
  level:
    root: INFO